server:
  port: 9314

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis:
  mapper-locations: classpath*:com/mufeng/vhr/mapper/**/*.xml

fastdfs:
  nginx:
    host: http://127.0.0.1/