server:
  port: 9312
spring:
  application:
    name: first-blog
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog_db?serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml